### ISSUE TITLE
Hey,your app is very useful to me, but how can I set my own password?

### ISSUE THREAD

**Issue by Skandinaviske** [paspao/MobiStego#3]
This app can perfectly protect one's message in the pictures.
I just find that every time when I want to decode,I must put into the password, but I didn't find someplace to set that.
And I also want to consult you a question, I have read some article that lsb algorithm just expends the 10% size of the whole picture.But I found your pictures expanded 20 times after I added some words into pictures,why is that?
Thx a lot for helping me.

**Comment by paspao** [comment]
HI @Skandinaviske,
when you hide a message, you can specify a password with a checkbox. Then in my example I encoded a msg **pippo** into an image of 772KB, the result image is 288KB

**Comment by Skandinaviske** [comment]
Thx for your answer, I found the checkbox.Best wish for you.
